name: deployment.yml

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-tags: 'true'
      - name: Login to GitHub container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '25'
          distribution: 'liberica'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
      - name: Tag and Push Calendar Version
        uses: anthonygrimes/calver-action@b3a8b326092c6b053bb2cb0f72a3e0e23b7715d1 # 2026.2.1
        id: versioning
      - name: Build and publish docker image to docker repository
        run: ./gradlew bootBuildImage --imageName=ghcr.io/anthonygrimes/hello-uuid:${{steps.versioning.outputs.version}}
